import { writeFileSync, readdirSync, readFileSync } from "fs"
import {
  getDistPath,
  makeGeneratedComment,
  findProjectRoot,
  tidyCss,
} from "../src/utils.js"
import { logGeneratedFiles } from "../src/cli.js"

import path from "path"

const root = findProjectRoot()
const pkg = JSON.parse(readFileSync(path.join(root, "package.json"), "utf8"))
const pkgName = pkg.name

/**
 * @param {string} dir
 * @param {string} ext
 */
function getFiles(dir, ext, exclude = []) {
  return readdirSync(getDistPath(dir)).filter(
    (f) => f.endsWith(ext) && f !== `all${ext}` && !exclude.includes(f),
  )
}

function stripGeneratedComment(css) {
  return css.replace(
    /\/\*\n\* This file is auto-generated by [^\n]+\n\*\/\n*/g,
    "",
  )
}

async function buildCss(dir, files) {
  const joinedFiles = files
    .map((f) =>
      stripGeneratedComment(
        readFileSync(getDistPath(`${dir}/${f}`), "utf8"),
      ).trim(),
    )
    .join("\n\n")

  return await tidyCss(joinedFiles)
}

async function buildScss(dir, files, scssFiles) {
  const imports = files.map((f) => `@use "${pkgName}/${dir}/${f}";`)
  const forwards = scssFiles.map((f) => `@forward "${pkgName}/${dir}/${f}";`)

  const joined = [...forwards, ...imports].join("\n")

  return await tidyCss(joined)
}

const comment = makeGeneratedComment(import.meta.url)

// Prefer colors.css over these -light/-dark files, it exports both sets
const visualsExcludes = [
  "colors-dark.css",
  "colors-light.css",
  "parties-light.css",
  "parties-dark.css",
]
const visualsCss = getFiles("visuals", ".css", visualsExcludes)
const visualsScss = getFiles("visuals", ".scss", visualsExcludes)

writeFileSync(
  getDistPath("visuals/all.css"),
  `${comment}\n\n${await buildCss("visuals", visualsCss)}\n`,
)

writeFileSync(
  getDistPath("visuals/all.scss"),
  `${comment}\n\n${await buildScss("visuals", visualsCss, visualsScss)}\n`,
)

// mq.scss already exports the $breakpoints variable
const sourceExcludes = ["breakpoints.scss", "font-faces.css"]
const sourceCss = getFiles("source", ".css", sourceExcludes)
const sourceScss = getFiles("source", ".scss", sourceExcludes)

writeFileSync(
  getDistPath("source/all.css"),
  `${comment}\n\n${await buildCss("source", sourceCss)}\n`,
)

writeFileSync(
  getDistPath("source/all.scss"),
  `${comment}\n\n${await buildScss("source", sourceCss, sourceScss)}\n`,
)

logGeneratedFiles(import.meta.filename, [
  getDistPath("visuals/all.css"),
  getDistPath("visuals/all.scss"),
  getDistPath("source/all.css"),
  getDistPath("source/all.scss"),
])
