import * as path from "path"
import * as fs from "fs"
import prettier from "prettier"
import { pxToRem as sourcePxToRem } from "@guardian/source/foundations"

/**
 * @param {string} [startDir]
 */
export function findProjectRoot(startDir = getMetaUrlDir(import.meta.url)) {
  let dir = startDir

  while (dir !== path.parse(dir).root) {
    if (fs.existsSync(path.join(dir, "node_modules"))) {
      return dir
    }

    dir = path.dirname(dir)
  }

  throw new Error('"node_modules" directory not found')
}

/**
 * @param {string} metaUrl
 */
export function getMetaUrlDir(metaUrl) {
  let dir = path.dirname(metaUrl)

  // Remove "file://" scheme
  if (dir.startsWith("file://")) {
    dir = dir.slice(7)
  }

  return dir
}

/**
 * @param {string} camelCaseName
 */
export function camelToKebab(camelCaseName) {
  return camelCaseName.replace(
    /[A-Z]+(?![a-z])|[A-Z]/g,
    ($, ofs) => (ofs ? "-" : "") + $.toLowerCase(),
  )
}

/**
 * @param {string} metaUrl import.meta.url of the generating script
 */
export function makeGeneratedComment(metaUrl) {
  // Remove "file://" scheme
  if (metaUrl.startsWith("file://")) {
    metaUrl = metaUrl.slice(7)
  }

  const relativePath = path.relative(findProjectRoot(), metaUrl)

  return `/*\n` + `* This file is auto-generated by ${relativePath}\n` + `*/`
}

/**
 * @param {string} generatorFilename
 * @param {string[]} [files]
 */
export function logGeneratedFiles(generatorFilename, files) {
  const root = findProjectRoot()
  const relativeGeneratorName = path.relative(root, generatorFilename)
  const relativeFiles = files.map((filename) => path.relative(root, filename))

  console.log(
    `${relativeGeneratorName} generated: ` +
      `\n  * ` +
      relativeFiles.join("\n  * ") +
      `\n`,
  )
}

/**
 * @param {string} relativePath Path relative to dist/
 */
export function getDistPath(relativePath) {
  const root = findProjectRoot()
  const fullPath = path.join(root, "dist", relativePath)
  const dir = path.dirname(fullPath)

  if (!fs.existsSync(dir)) {
    fs.mkdirSync(dir, { recursive: true })
  }

  return fullPath
}

/**
 * @param {string} percent
 */
export function percentToDecimal(percent) {
  const number = parseInt(percent)

  if (isNaN(number)) {
    throw new Error(`could not parse percentage "${percent}"`)
  }

  return number / 100
}

/**
 * @param {string} pxString eg. "16px"
 */
export function pxToRem(pxString) {
  const numPx = parseInt(pxString)

  if (isNaN(numPx)) {
    throw new Error(`could not parse percentage "${pxString}"`)
  }

  return sourcePxToRem(numPx)
}

/**
 * @param {string} css
 */
export async function tidyCss(css) {
  return prettier.format(css, { parser: "scss" })
}

/**
 * @param {string} css
 */
export function wrapDarkMode(css) {
  return (
    `@media (prefers-color-scheme: dark) {` +
    `\n  :root:not([data-color-scheme="light"]) body {` +
    `\n${css}` +
    `\n  }` +
    `\n}`
  )
}
